# Generated by Django 3.0.2 on 2020-01-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('start_date', models.DateField()),
                ('stop_date', models.DateField(blank=True)),
                ('short_blurb', models.TextField()),
                ('long_blurb', models.TextField()),
                ('code_link', models.URLField(blank=True)),
            ],
        ),
    ]
