# Generated by Django 3.0.2 on 2020-01-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_make_name_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='stop_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
